module.exports.ENCRYPTION_ALGORITHM = 'aes-256-cbc';
module.exports.KEY_LENGTH = 32;

const ipcMainListeners = {
  GENERATE_SALT: 'GENERATE_SALT',
  HASH_PASSWORD: 'HASH_PASSWORD',
  GET_ENV: 'GET_ENV',
  GET_ENV_SYNC: 'GET_ENV_SYNC',
  OPEN_EXTERNAL: 'OPEN_EXTERNAL',
  COPY_TO_CLIPBOARD: 'COPY_TO_CLIPBOARD',
  SAVE_PRIVATE_KEY: 'SAVE_PRIVATE_KEY',
  SAVE_KEY_PASSWORD: 'SAVE_KEY_PASSWORD',
  GET_PRIVATE_KEYS: 'GET_PRIVATEKEYS',
  GET_KEY_PASSWORDS: 'GET_KEY_PASSWORDS',
  SAVE_DATASTORE: 'SAVE_DATASTORE',
  GET_DATASTORE: 'GET_DATASTORE',
};
module.exports.ipcMainListeners = ipcMainListeners;
